const DEFAULT_PRODUCTS = [
  {
    id: 1,
    name: 'فيتامين C',
    price: 25,
    oldPrice: 32,
    inStock: true,
    category: 'health',
    categoryLabel: 'الصحة',
    icon: '🍊',
    desc: 'دعم المناعة والطاقة اليومية.',
    offer: true,
    isSensitive: false
  },
  {
    id: 2,
    name: 'كريم ترطيب طبي',
    price: 32,
    oldPrice: null,
    inStock: true,
    category: 'care',
    categoryLabel: 'العناية',
    icon: '🧴',
    desc: 'ترطيب لطيف للبشرة الجافة والحساسة.',
    isSensitive: false
  },
  {
    id: 3,
    name: 'واقي شمس',
    price: 45,
    oldPrice: 55,
    inStock: true,
    category: 'care',
    categoryLabel: 'العناية',
    icon: '☀️',
    desc: 'حماية يومية خفيفة ومناسبة للخروج.',
    offer: true,
    isSensitive: false
  },
  {
    id: 4,
    name: 'جهاز قياس حرارة',
    price: 55,
    oldPrice: null,
    inStock: false,
    category: 'health',
    categoryLabel: 'الصحة',
    icon: '🌡️',
    desc: 'قياس سريع ومناسب للاستخدام المنزلي.',
    isSensitive: false
  },
  {
    id: 5,
    name: 'شامبو طبي',
    price: 28,
    oldPrice: 35,
    inStock: true,
    category: 'beauty',
    categoryLabel: 'التجميل',
    icon: '🫧',
    desc: 'عناية نظيفة بفروة الرأس والشعر.',
    offer: true,
    isSensitive: true
  },
  {
    id: 6,
    name: 'مطهر يدين',
    price: 12,
    oldPrice: 15,
    inStock: true,
    category: 'care',
    categoryLabel: 'العناية',
    icon: '🧼',
    desc: 'تعقيم سريع بحجم مناسب للحقيبة.',
    offer: true,
    isSensitive: false
  },
  {
    id: 7,
    name: 'كولاجين عناية',
    price: 65,
    oldPrice: null,
    inStock: true,
    category: 'beauty',
    categoryLabel: 'التجميل',
    icon: '✨',
    desc: 'منتج جمالي بنمط عرض فاخر.',
    isSensitive: true
  },
  {
    id: 8,
    name: 'باقة العناية',
    price: 89,
    oldPrice: 110,
    inStock: true,
    category: 'offers',
    categoryLabel: 'العروض',
    icon: '🎁',
    desc: 'مجموعة منتجات بسعر عرض محدود.',
    offer: true,
    isSensitive: true
  }
];
